AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket with policy allowing EC2 role read access

Parameters:
  IAMRoleARN:
    Type: String
    Description: IAM Role that gives access to the ec2 instance to s3 buckets 
    # tiene que ser un valor con la forma arn:aws:iam::account-id:role/role-name
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
    Default: time-app-backend-bucket

Resources:
  BackendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              
  # S3 Bucket Policy to allow EC2 role read access
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BackendS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEC2RoleReadAccess
            Effect: Allow
            Principal:
              AWS: !Ref IAMRoleARN
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*
