AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket with policy allowing EC2 role read access
# Vamos a desplegar un bucket s3 para subir todos los archivos necesarios para la aplicacion y vamos a asignarle una politica de 
# acceso a los EC2 generados por el template de core-infra
Resources:
  BackendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: time-app-backend-bucket # Si se cambia el nombre del bucket tambien se debe cambiar en el archivo boostrap.sh
      PublicAccessBlockConfiguration: # Se bloquea todo el acceso publico al contenido del bucket
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  # En este caso necesitamos definir un Bucket Policy que nos permita darle acceso 
  # a las instancias EC2 con el role EMR_EC2_DefaultRole a los documentos dentro del bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BackendS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEC2RoleReadAccess
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::984332661247:role/EMR_EC2_DefaultRole
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: #damos acceso al bucket y a todo el contenido en su interior
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*
